### ISSUE TITLE
还是跳转到了桌面端

### ISSUE THREAD

**Issue by Huang-Libo** [XhstormR/BaiduNetdisk-WAP#1]
加载控件后, 点击 Read me 中的 https://pan.baidu.com/wap/home, 还是跳转到了桌面端.

**Comment by XhstormR** [comment]
我这里没有问题啊，不知道你的环境是什么。

建议：
1. 重启游览器。
2. 重新下载扩展 -> 解压 -> 重新加载扩展。
3. 清空百度 Cookie。

**Comment by Huang-Libo** [comment]
macOS 10.12.3 
Chrome v56.0 64bit (最新版)

按照步骤做了还是不行

**Comment by XhstormR** [comment]
在百度网盘进入 Chrome 控制台，输入 `navigator.platform`，输出的是什么？

**Comment by Huang-Libo** [comment]
"Android"

浏览器显示的网站是 https://pan.baidu.com/

这算跳转了吗?

**Comment by XhstormR** [comment]
按理说在 https://pan.baidu.com/disk/home#list/path=%2F&vmode=list 下，控制台，输入  `navigator.platform` ,若显示 "Android" 。

那么访问 https://pan.baidu.com/wap/home ，应该不会跳转至 PC 界面啊。

有可能是其他扩展干扰了，我这里是正常使用的。

再不然只有远程看看了。

**Comment by XhstormR** [comment]
暂时关闭。
