### ISSUE TITLE
BaiduNetdisk

### ISSUE THREAD

**Issue by pac20** [XhstormR/BaiduNetdisk-WAP#2]
Hi XhstormR.I russian user Baidu Cloud.I have free account.This is the first my cloud and now i testing cloud on bags.I already tested PC version cloud and now testing android version cloud.You could not help me.I need android software or additions from mobile browsers which could create links for downloads files and folders.In general, you hope you understand what I'm writing about.I testing on smatfone with android 6.0.Smartfone is not root.Hi has memory card
integrated on system. I would like you to answer.

**Comment by XhstormR** [comment]
This is a Chrome extension, which means that it can only be installed on a PC browser. I can do nothing on Android.

**Comment by pac20** [comment]
Very sorry. I thought that you would help the Russian segment of the Baidu cloud.You use it yourself?

**Comment by XhstormR** [comment]
Yeah, I am not a Baidu employee, i wrote this just for fun.

**Comment by pac20** [comment]
Your work is awakened and maybe someone else can turn to you. I link to your profile in the Russian segment of the Internet. Maybe I should turn to you from Russia for help. I live in Primorsky Krai (Vladivostok). You can write in what area of development you work hard.
And about Baidu. You can write to me how things are with you at the speed of downloading and uploading to Baidu.
The fact is that I have a few friends live in China (bloggers from Russia) who then in Guangzhou someone in Heihe.I they zainisovany in use Baidu.No them primarily are interested in what speed in the free mode of use.
sorry for my English

**Comment by pac20** [comment]
And since you use Aria2 I want to tell you that there is already a version for android https://github.com/chdir .True it is still in the beta test.Developer Russian but friendly with English

**Comment by XhstormR** [comment]
Thanks for your advice.
